[package]
name = "al-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
rust-stemmers = "1.2"
stopwords = "0.4"
rayon = "1.8"
indicatif = "0.17"
kmeans = "2.0.1"
hamming = "0.1"
pyo3 = { version = "0.21", features = ["extension-module"] }

[lib]
crate-type = ["cdylib"]
name = "al_rust"